# Generated by Django 4.2.23 on 2025-09-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='default fullname', editable=False, max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'first_name', 'last_name'), name='unique_client_name_per_company'),
        ),
    ]
