# Generated by Django 4.2.23 on 2025-09-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('clients', '0002_alter_client_options_client_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company'),
        ),
    ]
