# Generated by Django 4.2.23 on 2025-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_mime_type_document_original_filename_and_more'),
        ('clients', '0003_alter_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='clients', to='documents.document'),
        ),
    ]
