# Generated by Django 4.2.23 on 2025-09-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_mime_type_document_original_filename_and_more'),
        ('clients', '0004_client_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='documents',
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documents.document')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_documents', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
            },
            bases=('documents.document',),
        ),
    ]
