# Generated by Django 4.2.23 on 2025-10-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_documents_clientdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDocument',
        ),
    ]
