# Generated by Django 4.2.23 on 2026-03-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
