# Generated by Django 4.2.23 on 2026-03-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_options'),
        ('clients', '0009_alter_client_options_alter_client_phone_secondary'),
    ]

    operations = [
    ]
