# Generated by Django 4.2.23 on 2026-04-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacttag_color'),
        ('jobs', '0002_alter_job_assignee_alter_job_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_referred_by', to='contacts.contact'),
        ),
    ]
