# Generated by Django 4.2.23 on 2026-06-06 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_contacttag_color'),
        ('jobs', '0005_jobexpensecategory_remove_historicaljob_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexpense',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='jobexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobexpense',
            name='job',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='label',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='job',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='job',
            name='label',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='job',
            name='representative',
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='estimated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='jobs_assignees', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='jobs_recipients', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='job',
            name='representatives',
            field=models.ManyToManyField(blank=True, related_name='jobs_representatives', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='job',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicaljobcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicaljobcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaljobcomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='job',
            name='categories',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='job',
            name='referred_by',
        ),
        migrations.AlterField(
            model_name='jobcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobcomment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_comments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcomment',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_comments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalJobExpense',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='JobExpense',
        ),
        migrations.DeleteModel(
            name='JobExpenseCategory',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='referred_by',
            field=models.ManyToManyField(blank=True, related_name='jobs_referred_by', to='contacts.contact'),
        ),
    ]
