# Generated by Django 4.2.23 on 2026-07-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_jobexpense_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
