# Generated by Django 4.2.23 on 2026-07-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_historicaljob_cancelled_at_job_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
