# Generated by Django 4.2.23 on 2025-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
