# Generated by Django 4.2.23 on 2025-08-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='title',
            new_name='label',
        ),
    ]
