# Generated by Django 4.2.23 on 2025-09-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('work_orders', '0002_alter_workorder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
