# Generated by Django 4.2.23 on 2025-08-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
        ('work_orders', '0002_alter_workorder_options_rename_title_workorder_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='companies.company'),
        ),
    ]
