# Generated by Django 4.2.23 on 2025-09-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('work_orders', '0003_alter_workorder_company_alter_workorder_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='companies.company'),
        ),
    ]
