# Generated by Django 4.2.23 on 2025-08-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_workorder_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='company',
        ),
    ]
