# Generated by Django 4.2.23 on 2025-09-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_workorder_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='documents',
        ),
    ]
