# Generated by Django 4.2.23 on 2026-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('work_orders', '0006_remove_workorder_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='workorder',
            unique_together={('company', 'label')},
        ),
    ]
