# Generated by Django 4.2.23 on 2026-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_place_id', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(editable=False, max_length=10)),
                ('state', models.CharField(editable=False, max_length=100)),
                ('city', models.CharField(editable=False, max_length=100)),
                ('postal_code', models.CharField(editable=False, max_length=20)),
                ('address_full', models.TextField(editable=False, max_length=500)),
                ('address_short', models.TextField(editable=False, max_length=255)),
                ('latitude', models.FloatField(editable=False)),
                ('longitude', models.FloatField(editable=False)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
    ]
