# Generated by Django 4.2.23 on 2026-05-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_full',
            field=models.CharField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_short',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
