# Generated by Django 4.2.23 on 2025-09-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='google_place_id',
        ),
    ]
