# Generated by Django 4.2.23 on 2025-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_place_id_place_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address_full',
            field=models.TextField(editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='address_short',
            field=models.TextField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
