# Generated by Django 4.2.23 on 2025-09-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('places', '0003_alter_place_address_full_alter_place_address_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='place',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
