# Generated by Django 4.2.23 on 2025-09-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_company_alter_place_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
