# Generated by Django 4.2.23 on 2025-09-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('places', '0005_alter_place_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='companies.company'),
        ),
    ]
