# Generated by Django 4.2.23 on 2026-02-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('places', '0006_alter_place_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('company', 'google_place_id')},
        ),
    ]
