# Generated by Django 4.2.23 on 2025-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0003_document_mime_type_document_original_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'),
        ),
    ]
