# Generated by Django 4.2.23 on 2026-03-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttag',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
