# Generated by Django 4.2.23 on 2026-06-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contacttag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ContactTag',
        ),
    ]
