/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPlacesRouteImport } from './routes/app/places'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppContactsRouteImport } from './routes/app/contacts'
import { Route as AppBoardRouteImport } from './routes/app/board'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppPlacesIndexRouteImport } from './routes/app/places/index'
import { Route as AppJobsIndexRouteImport } from './routes/app/jobs/index'
import { Route as AppContactsIndexRouteImport } from './routes/app/contacts/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as ResetPasswordEncodedUserIdTokenRouteImport } from './routes/reset-password.$encodedUserId.$token'
import { Route as AppProfileIdRouteImport } from './routes/app/profile.$id'
import { Route as AppPlacesIdRouteImport } from './routes/app/places/$id'
import { Route as AppJobsCreateRouteImport } from './routes/app/jobs/create'
import { Route as AppJobsIdRouteImport } from './routes/app/jobs/$id'
import { Route as AppContactsCreateRouteImport } from './routes/app/contacts/create'
import { Route as AppContactsIdRouteImport } from './routes/app/contacts/$id'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppJobsIdIndexRouteImport } from './routes/app/jobs/$id/index'
import { Route as AppContactsIdIndexRouteImport } from './routes/app/contacts/$id/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppJobsIdEditRouteImport } from './routes/app/jobs/$id/edit'
import { Route as AppContactsIdEditRouteImport } from './routes/app/contacts/$id/edit'
import { Route as AppAdminUsersCreateRouteImport } from './routes/app/admin/users/create'
import { Route as AppAdminUsersIdRouteImport } from './routes/app/admin/users/$id'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesIndexRoute = AppPlacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlacesRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ResetPasswordEncodedUserIdTokenRoute =
  ResetPasswordEncodedUserIdTokenRouteImport.update({
    id: '/reset-password/$encodedUserId/$token',
    path: '/reset-password/$encodedUserId/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesIdRoute = AppPlacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPlacesRoute,
} as any)
const AppJobsCreateRoute = AppJobsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppContactsCreateRoute = AppContactsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppContactsRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppJobsIdIndexRoute = AppJobsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppContactsIdIndexRoute = AppContactsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContactsIdRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppJobsIdEditRoute = AppJobsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppJobsIdRoute,
} as any)
const AppContactsIdEditRoute = AppContactsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppContactsIdRoute,
} as any)
const AppAdminUsersCreateRoute = AppAdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/board': typeof AppBoardRoute
  '/app/contacts': typeof AppContactsRouteWithChildren
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/places': typeof AppPlacesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/contacts/$id': typeof AppContactsIdRouteWithChildren
  '/app/contacts/create': typeof AppContactsCreateRoute
  '/app/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/app/jobs/create': typeof AppJobsCreateRoute
  '/app/places/$id': typeof AppPlacesIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/places/': typeof AppPlacesIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/contacts/$id/edit': typeof AppContactsIdEditRoute
  '/app/jobs/$id/edit': typeof AppJobsIdEditRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/contacts/$id/': typeof AppContactsIdIndexRoute
  '/app/jobs/$id/': typeof AppJobsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/board': typeof AppBoardRoute
  '/app': typeof AppIndexRoute
  '/app/contacts/create': typeof AppContactsCreateRoute
  '/app/jobs/create': typeof AppJobsCreateRoute
  '/app/places/$id': typeof AppPlacesIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/contacts': typeof AppContactsIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/app/places': typeof AppPlacesIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/contacts/$id/edit': typeof AppContactsIdEditRoute
  '/app/jobs/$id/edit': typeof AppJobsIdEditRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/contacts/$id': typeof AppContactsIdIndexRoute
  '/app/jobs/$id': typeof AppJobsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/board': typeof AppBoardRoute
  '/app/contacts': typeof AppContactsRouteWithChildren
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/places': typeof AppPlacesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/contacts/$id': typeof AppContactsIdRouteWithChildren
  '/app/contacts/create': typeof AppContactsCreateRoute
  '/app/jobs/$id': typeof AppJobsIdRouteWithChildren
  '/app/jobs/create': typeof AppJobsCreateRoute
  '/app/places/$id': typeof AppPlacesIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/contacts/': typeof AppContactsIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/places/': typeof AppPlacesIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/contacts/$id/edit': typeof AppContactsIdEditRoute
  '/app/jobs/$id/edit': typeof AppJobsIdEditRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/contacts/$id/': typeof AppContactsIdIndexRoute
  '/app/jobs/$id/': typeof AppJobsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/admin'
    | '/app/board'
    | '/app/contacts'
    | '/app/jobs'
    | '/app/places'
    | '/app/'
    | '/app/admin/users'
    | '/app/contacts/$id'
    | '/app/contacts/create'
    | '/app/jobs/$id'
    | '/app/jobs/create'
    | '/app/places/$id'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin/'
    | '/app/contacts/'
    | '/app/jobs/'
    | '/app/places/'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/contacts/$id/edit'
    | '/app/jobs/$id/edit'
    | '/app/admin/users/'
    | '/app/contacts/$id/'
    | '/app/jobs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/board'
    | '/app'
    | '/app/contacts/create'
    | '/app/jobs/create'
    | '/app/places/$id'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin'
    | '/app/contacts'
    | '/app/jobs'
    | '/app/places'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/contacts/$id/edit'
    | '/app/jobs/$id/edit'
    | '/app/admin/users'
    | '/app/contacts/$id'
    | '/app/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/admin'
    | '/app/board'
    | '/app/contacts'
    | '/app/jobs'
    | '/app/places'
    | '/app/'
    | '/app/admin/users'
    | '/app/contacts/$id'
    | '/app/contacts/create'
    | '/app/jobs/$id'
    | '/app/jobs/create'
    | '/app/places/$id'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin/'
    | '/app/contacts/'
    | '/app/jobs/'
    | '/app/places/'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/contacts/$id/edit'
    | '/app/jobs/$id/edit'
    | '/app/admin/users/'
    | '/app/contacts/$id/'
    | '/app/jobs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ResetPasswordEncodedUserIdTokenRoute: typeof ResetPasswordEncodedUserIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/places': {
      id: '/app/places'
      path: '/places'
      fullPath: '/app/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/places/': {
      id: '/app/places/'
      path: '/'
      fullPath: '/app/places/'
      preLoaderRoute: typeof AppPlacesIndexRouteImport
      parentRoute: typeof AppPlacesRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/contacts/': {
      id: '/app/contacts/'
      path: '/'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/reset-password/$encodedUserId/$token': {
      id: '/reset-password/$encodedUserId/$token'
      path: '/reset-password/$encodedUserId/$token'
      fullPath: '/reset-password/$encodedUserId/$token'
      preLoaderRoute: typeof ResetPasswordEncodedUserIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/profile/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/places/$id': {
      id: '/app/places/$id'
      path: '/$id'
      fullPath: '/app/places/$id'
      preLoaderRoute: typeof AppPlacesIdRouteImport
      parentRoute: typeof AppPlacesRoute
    }
    '/app/jobs/create': {
      id: '/app/jobs/create'
      path: '/create'
      fullPath: '/app/jobs/create'
      preLoaderRoute: typeof AppJobsCreateRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/contacts/create': {
      id: '/app/contacts/create'
      path: '/create'
      fullPath: '/app/contacts/create'
      preLoaderRoute: typeof AppContactsCreateRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/app/contacts/$id': {
      id: '/app/contacts/$id'
      path: '/$id'
      fullPath: '/app/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppContactsRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/jobs/$id/': {
      id: '/app/jobs/$id/'
      path: '/'
      fullPath: '/app/jobs/$id/'
      preLoaderRoute: typeof AppJobsIdIndexRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/app/contacts/$id/': {
      id: '/app/contacts/$id/'
      path: '/'
      fullPath: '/app/contacts/$id/'
      preLoaderRoute: typeof AppContactsIdIndexRouteImport
      parentRoute: typeof AppContactsIdRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/jobs/$id/edit': {
      id: '/app/jobs/$id/edit'
      path: '/edit'
      fullPath: '/app/jobs/$id/edit'
      preLoaderRoute: typeof AppJobsIdEditRouteImport
      parentRoute: typeof AppJobsIdRoute
    }
    '/app/contacts/$id/edit': {
      id: '/app/contacts/$id/edit'
      path: '/edit'
      fullPath: '/app/contacts/$id/edit'
      preLoaderRoute: typeof AppContactsIdEditRouteImport
      parentRoute: typeof AppContactsIdRoute
    }
    '/app/admin/users/create': {
      id: '/app/admin/users/create'
      path: '/create'
      fullPath: '/app/admin/users/create'
      preLoaderRoute: typeof AppAdminUsersCreateRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/admin/users/$id': {
      id: '/app/admin/users/$id'
      path: '/$id'
      fullPath: '/app/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAdminUsersCreateRoute: typeof AppAdminUsersCreateRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAdminUsersCreateRoute: AppAdminUsersCreateRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppContactsIdRouteChildren {
  AppContactsIdEditRoute: typeof AppContactsIdEditRoute
  AppContactsIdIndexRoute: typeof AppContactsIdIndexRoute
}

const AppContactsIdRouteChildren: AppContactsIdRouteChildren = {
  AppContactsIdEditRoute: AppContactsIdEditRoute,
  AppContactsIdIndexRoute: AppContactsIdIndexRoute,
}

const AppContactsIdRouteWithChildren = AppContactsIdRoute._addFileChildren(
  AppContactsIdRouteChildren,
)

interface AppContactsRouteChildren {
  AppContactsIdRoute: typeof AppContactsIdRouteWithChildren
  AppContactsCreateRoute: typeof AppContactsCreateRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
}

const AppContactsRouteChildren: AppContactsRouteChildren = {
  AppContactsIdRoute: AppContactsIdRouteWithChildren,
  AppContactsCreateRoute: AppContactsCreateRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
}

const AppContactsRouteWithChildren = AppContactsRoute._addFileChildren(
  AppContactsRouteChildren,
)

interface AppJobsIdRouteChildren {
  AppJobsIdEditRoute: typeof AppJobsIdEditRoute
  AppJobsIdIndexRoute: typeof AppJobsIdIndexRoute
}

const AppJobsIdRouteChildren: AppJobsIdRouteChildren = {
  AppJobsIdEditRoute: AppJobsIdEditRoute,
  AppJobsIdIndexRoute: AppJobsIdIndexRoute,
}

const AppJobsIdRouteWithChildren = AppJobsIdRoute._addFileChildren(
  AppJobsIdRouteChildren,
)

interface AppJobsRouteChildren {
  AppJobsIdRoute: typeof AppJobsIdRouteWithChildren
  AppJobsCreateRoute: typeof AppJobsCreateRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsIdRoute: AppJobsIdRouteWithChildren,
  AppJobsCreateRoute: AppJobsCreateRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppPlacesRouteChildren {
  AppPlacesIdRoute: typeof AppPlacesIdRoute
  AppPlacesIndexRoute: typeof AppPlacesIndexRoute
}

const AppPlacesRouteChildren: AppPlacesRouteChildren = {
  AppPlacesIdRoute: AppPlacesIdRoute,
  AppPlacesIndexRoute: AppPlacesIndexRoute,
}

const AppPlacesRouteWithChildren = AppPlacesRoute._addFileChildren(
  AppPlacesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBoardRoute: typeof AppBoardRoute
  AppContactsRoute: typeof AppContactsRouteWithChildren
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppPlacesRoute: typeof AppPlacesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBoardRoute: AppBoardRoute,
  AppContactsRoute: AppContactsRouteWithChildren,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppPlacesRoute: AppPlacesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProfileIdRoute: AppProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ResetPasswordEncodedUserIdTokenRoute: ResetPasswordEncodedUserIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
