/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSandboxRouteImport } from './routes/app/sandbox'
import { Route as AppDirectoryRouteImport } from './routes/app/directory'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppDirectoryIndexRouteImport } from './routes/app/directory/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as ResetPasswordEncodedUserIdTokenRouteImport } from './routes/reset-password.$encodedUserId.$token'
import { Route as AppProfileIdRouteImport } from './routes/app/profile.$id'
import { Route as AppDirectoryPlacesRouteImport } from './routes/app/directory/places'
import { Route as AppDirectoryContactsRouteImport } from './routes/app/directory/contacts'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppDirectoryPlacesIndexRouteImport } from './routes/app/directory/places/index'
import { Route as AppDirectoryContactsIndexRouteImport } from './routes/app/directory/contacts/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/app/admin/users/index'
import { Route as AppDirectoryPlacesCreateRouteImport } from './routes/app/directory/places/create'
import { Route as AppDirectoryPlacesIdRouteImport } from './routes/app/directory/places/$id'
import { Route as AppDirectoryContactsCreateRouteImport } from './routes/app/directory/contacts/create'
import { Route as AppDirectoryContactsIdRouteImport } from './routes/app/directory/contacts/$id'
import { Route as AppAdminUsersCreateRouteImport } from './routes/app/admin/users/create'
import { Route as AppAdminUsersIdRouteImport } from './routes/app/admin/users/$id'
import { Route as AppDirectoryPlacesIdIndexRouteImport } from './routes/app/directory/places/$id/index'
import { Route as AppDirectoryContactsIdIndexRouteImport } from './routes/app/directory/contacts/$id/index'
import { Route as AppDirectoryPlacesIdEditRouteImport } from './routes/app/directory/places/$id/edit'
import { Route as AppDirectoryContactsIdEditRouteImport } from './routes/app/directory/contacts/$id/edit'

const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSandboxRoute = AppSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryIndexRoute = AppDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDirectoryRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const ResetPasswordEncodedUserIdTokenRoute =
  ResetPasswordEncodedUserIdTokenRouteImport.update({
    id: '/reset-password/$encodedUserId/$token',
    path: '/reset-password/$encodedUserId/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryPlacesRoute = AppDirectoryPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppDirectoryRoute,
} as any)
const AppDirectoryContactsRoute = AppDirectoryContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppDirectoryRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppDirectoryPlacesIndexRoute = AppDirectoryPlacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDirectoryPlacesRoute,
} as any)
const AppDirectoryContactsIndexRoute =
  AppDirectoryContactsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDirectoryContactsRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppDirectoryPlacesCreateRoute =
  AppDirectoryPlacesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppDirectoryPlacesRoute,
  } as any)
const AppDirectoryPlacesIdRoute = AppDirectoryPlacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDirectoryPlacesRoute,
} as any)
const AppDirectoryContactsCreateRoute =
  AppDirectoryContactsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppDirectoryContactsRoute,
  } as any)
const AppDirectoryContactsIdRoute = AppDirectoryContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDirectoryContactsRoute,
} as any)
const AppAdminUsersCreateRoute = AppAdminUsersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAdminUsersRoute,
} as any)
const AppDirectoryPlacesIdIndexRoute =
  AppDirectoryPlacesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDirectoryPlacesIdRoute,
  } as any)
const AppDirectoryContactsIdIndexRoute =
  AppDirectoryContactsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDirectoryContactsIdRoute,
  } as any)
const AppDirectoryPlacesIdEditRoute =
  AppDirectoryPlacesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppDirectoryPlacesIdRoute,
  } as any)
const AppDirectoryContactsIdEditRoute =
  AppDirectoryContactsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppDirectoryContactsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRouteWithChildren
  '/app/sandbox': typeof AppSandboxRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/directory/contacts': typeof AppDirectoryContactsRouteWithChildren
  '/app/directory/places': typeof AppDirectoryPlacesRouteWithChildren
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/directory/': typeof AppDirectoryIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/directory/contacts/$id': typeof AppDirectoryContactsIdRouteWithChildren
  '/app/directory/contacts/create': typeof AppDirectoryContactsCreateRoute
  '/app/directory/places/$id': typeof AppDirectoryPlacesIdRouteWithChildren
  '/app/directory/places/create': typeof AppDirectoryPlacesCreateRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/directory/contacts/': typeof AppDirectoryContactsIndexRoute
  '/app/directory/places/': typeof AppDirectoryPlacesIndexRoute
  '/app/directory/contacts/$id/edit': typeof AppDirectoryContactsIdEditRoute
  '/app/directory/places/$id/edit': typeof AppDirectoryPlacesIdEditRoute
  '/app/directory/contacts/$id/': typeof AppDirectoryContactsIdIndexRoute
  '/app/directory/places/$id/': typeof AppDirectoryPlacesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/sandbox': typeof AppSandboxRoute
  '/app': typeof AppIndexRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/directory': typeof AppDirectoryIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/directory/contacts/create': typeof AppDirectoryContactsCreateRoute
  '/app/directory/places/create': typeof AppDirectoryPlacesCreateRoute
  '/app/admin/users': typeof AppAdminUsersIndexRoute
  '/app/directory/contacts': typeof AppDirectoryContactsIndexRoute
  '/app/directory/places': typeof AppDirectoryPlacesIndexRoute
  '/app/directory/contacts/$id/edit': typeof AppDirectoryContactsIdEditRoute
  '/app/directory/places/$id/edit': typeof AppDirectoryPlacesIdEditRoute
  '/app/directory/contacts/$id': typeof AppDirectoryContactsIdIndexRoute
  '/app/directory/places/$id': typeof AppDirectoryPlacesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRouteWithChildren
  '/app/sandbox': typeof AppSandboxRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/app/directory/contacts': typeof AppDirectoryContactsRouteWithChildren
  '/app/directory/places': typeof AppDirectoryPlacesRouteWithChildren
  '/app/profile/$id': typeof AppProfileIdRoute
  '/reset-password/$encodedUserId/$token': typeof ResetPasswordEncodedUserIdTokenRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/directory/': typeof AppDirectoryIndexRoute
  '/app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/app/admin/users/create': typeof AppAdminUsersCreateRoute
  '/app/directory/contacts/$id': typeof AppDirectoryContactsIdRouteWithChildren
  '/app/directory/contacts/create': typeof AppDirectoryContactsCreateRoute
  '/app/directory/places/$id': typeof AppDirectoryPlacesIdRouteWithChildren
  '/app/directory/places/create': typeof AppDirectoryPlacesCreateRoute
  '/app/admin/users/': typeof AppAdminUsersIndexRoute
  '/app/directory/contacts/': typeof AppDirectoryContactsIndexRoute
  '/app/directory/places/': typeof AppDirectoryPlacesIndexRoute
  '/app/directory/contacts/$id/edit': typeof AppDirectoryContactsIdEditRoute
  '/app/directory/places/$id/edit': typeof AppDirectoryPlacesIdEditRoute
  '/app/directory/contacts/$id/': typeof AppDirectoryContactsIdIndexRoute
  '/app/directory/places/$id/': typeof AppDirectoryPlacesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/sandbox'
    | '/app/'
    | '/app/admin/users'
    | '/app/directory/contacts'
    | '/app/directory/places'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin/'
    | '/app/directory/'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/directory/contacts/$id'
    | '/app/directory/contacts/create'
    | '/app/directory/places/$id'
    | '/app/directory/places/create'
    | '/app/admin/users/'
    | '/app/directory/contacts/'
    | '/app/directory/places/'
    | '/app/directory/contacts/$id/edit'
    | '/app/directory/places/$id/edit'
    | '/app/directory/contacts/$id/'
    | '/app/directory/places/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/dashboard'
    | '/app/sandbox'
    | '/app'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin'
    | '/app/directory'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/directory/contacts/create'
    | '/app/directory/places/create'
    | '/app/admin/users'
    | '/app/directory/contacts'
    | '/app/directory/places'
    | '/app/directory/contacts/$id/edit'
    | '/app/directory/places/$id/edit'
    | '/app/directory/contacts/$id'
    | '/app/directory/places/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-out'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/sandbox'
    | '/app/'
    | '/app/admin/users'
    | '/app/directory/contacts'
    | '/app/directory/places'
    | '/app/profile/$id'
    | '/reset-password/$encodedUserId/$token'
    | '/app/admin/'
    | '/app/directory/'
    | '/app/admin/users/$id'
    | '/app/admin/users/create'
    | '/app/directory/contacts/$id'
    | '/app/directory/contacts/create'
    | '/app/directory/places/$id'
    | '/app/directory/places/create'
    | '/app/admin/users/'
    | '/app/directory/contacts/'
    | '/app/directory/places/'
    | '/app/directory/contacts/$id/edit'
    | '/app/directory/places/$id/edit'
    | '/app/directory/contacts/$id/'
    | '/app/directory/places/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  ResetPasswordEncodedUserIdTokenRoute: typeof ResetPasswordEncodedUserIdTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sandbox': {
      id: '/app/sandbox'
      path: '/sandbox'
      fullPath: '/app/sandbox'
      preLoaderRoute: typeof AppSandboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory': {
      id: '/app/directory'
      path: '/directory'
      fullPath: '/app/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory/': {
      id: '/app/directory/'
      path: '/'
      fullPath: '/app/directory/'
      preLoaderRoute: typeof AppDirectoryIndexRouteImport
      parentRoute: typeof AppDirectoryRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/reset-password/$encodedUserId/$token': {
      id: '/reset-password/$encodedUserId/$token'
      path: '/reset-password/$encodedUserId/$token'
      fullPath: '/reset-password/$encodedUserId/$token'
      preLoaderRoute: typeof ResetPasswordEncodedUserIdTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/profile/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory/places': {
      id: '/app/directory/places'
      path: '/places'
      fullPath: '/app/directory/places'
      preLoaderRoute: typeof AppDirectoryPlacesRouteImport
      parentRoute: typeof AppDirectoryRoute
    }
    '/app/directory/contacts': {
      id: '/app/directory/contacts'
      path: '/contacts'
      fullPath: '/app/directory/contacts'
      preLoaderRoute: typeof AppDirectoryContactsRouteImport
      parentRoute: typeof AppDirectoryRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/directory/places/': {
      id: '/app/directory/places/'
      path: '/'
      fullPath: '/app/directory/places/'
      preLoaderRoute: typeof AppDirectoryPlacesIndexRouteImport
      parentRoute: typeof AppDirectoryPlacesRoute
    }
    '/app/directory/contacts/': {
      id: '/app/directory/contacts/'
      path: '/'
      fullPath: '/app/directory/contacts/'
      preLoaderRoute: typeof AppDirectoryContactsIndexRouteImport
      parentRoute: typeof AppDirectoryContactsRoute
    }
    '/app/admin/users/': {
      id: '/app/admin/users/'
      path: '/'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/directory/places/create': {
      id: '/app/directory/places/create'
      path: '/create'
      fullPath: '/app/directory/places/create'
      preLoaderRoute: typeof AppDirectoryPlacesCreateRouteImport
      parentRoute: typeof AppDirectoryPlacesRoute
    }
    '/app/directory/places/$id': {
      id: '/app/directory/places/$id'
      path: '/$id'
      fullPath: '/app/directory/places/$id'
      preLoaderRoute: typeof AppDirectoryPlacesIdRouteImport
      parentRoute: typeof AppDirectoryPlacesRoute
    }
    '/app/directory/contacts/create': {
      id: '/app/directory/contacts/create'
      path: '/create'
      fullPath: '/app/directory/contacts/create'
      preLoaderRoute: typeof AppDirectoryContactsCreateRouteImport
      parentRoute: typeof AppDirectoryContactsRoute
    }
    '/app/directory/contacts/$id': {
      id: '/app/directory/contacts/$id'
      path: '/$id'
      fullPath: '/app/directory/contacts/$id'
      preLoaderRoute: typeof AppDirectoryContactsIdRouteImport
      parentRoute: typeof AppDirectoryContactsRoute
    }
    '/app/admin/users/create': {
      id: '/app/admin/users/create'
      path: '/create'
      fullPath: '/app/admin/users/create'
      preLoaderRoute: typeof AppAdminUsersCreateRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/admin/users/$id': {
      id: '/app/admin/users/$id'
      path: '/$id'
      fullPath: '/app/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/app/directory/places/$id/': {
      id: '/app/directory/places/$id/'
      path: '/'
      fullPath: '/app/directory/places/$id/'
      preLoaderRoute: typeof AppDirectoryPlacesIdIndexRouteImport
      parentRoute: typeof AppDirectoryPlacesIdRoute
    }
    '/app/directory/contacts/$id/': {
      id: '/app/directory/contacts/$id/'
      path: '/'
      fullPath: '/app/directory/contacts/$id/'
      preLoaderRoute: typeof AppDirectoryContactsIdIndexRouteImport
      parentRoute: typeof AppDirectoryContactsIdRoute
    }
    '/app/directory/places/$id/edit': {
      id: '/app/directory/places/$id/edit'
      path: '/edit'
      fullPath: '/app/directory/places/$id/edit'
      preLoaderRoute: typeof AppDirectoryPlacesIdEditRouteImport
      parentRoute: typeof AppDirectoryPlacesIdRoute
    }
    '/app/directory/contacts/$id/edit': {
      id: '/app/directory/contacts/$id/edit'
      path: '/edit'
      fullPath: '/app/directory/contacts/$id/edit'
      preLoaderRoute: typeof AppDirectoryContactsIdEditRouteImport
      parentRoute: typeof AppDirectoryContactsIdRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAdminUsersCreateRoute: typeof AppAdminUsersCreateRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAdminUsersCreateRoute: AppAdminUsersCreateRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDirectoryContactsIdRouteChildren {
  AppDirectoryContactsIdEditRoute: typeof AppDirectoryContactsIdEditRoute
  AppDirectoryContactsIdIndexRoute: typeof AppDirectoryContactsIdIndexRoute
}

const AppDirectoryContactsIdRouteChildren: AppDirectoryContactsIdRouteChildren =
  {
    AppDirectoryContactsIdEditRoute: AppDirectoryContactsIdEditRoute,
    AppDirectoryContactsIdIndexRoute: AppDirectoryContactsIdIndexRoute,
  }

const AppDirectoryContactsIdRouteWithChildren =
  AppDirectoryContactsIdRoute._addFileChildren(
    AppDirectoryContactsIdRouteChildren,
  )

interface AppDirectoryContactsRouteChildren {
  AppDirectoryContactsIdRoute: typeof AppDirectoryContactsIdRouteWithChildren
  AppDirectoryContactsCreateRoute: typeof AppDirectoryContactsCreateRoute
  AppDirectoryContactsIndexRoute: typeof AppDirectoryContactsIndexRoute
}

const AppDirectoryContactsRouteChildren: AppDirectoryContactsRouteChildren = {
  AppDirectoryContactsIdRoute: AppDirectoryContactsIdRouteWithChildren,
  AppDirectoryContactsCreateRoute: AppDirectoryContactsCreateRoute,
  AppDirectoryContactsIndexRoute: AppDirectoryContactsIndexRoute,
}

const AppDirectoryContactsRouteWithChildren =
  AppDirectoryContactsRoute._addFileChildren(AppDirectoryContactsRouteChildren)

interface AppDirectoryPlacesIdRouteChildren {
  AppDirectoryPlacesIdEditRoute: typeof AppDirectoryPlacesIdEditRoute
  AppDirectoryPlacesIdIndexRoute: typeof AppDirectoryPlacesIdIndexRoute
}

const AppDirectoryPlacesIdRouteChildren: AppDirectoryPlacesIdRouteChildren = {
  AppDirectoryPlacesIdEditRoute: AppDirectoryPlacesIdEditRoute,
  AppDirectoryPlacesIdIndexRoute: AppDirectoryPlacesIdIndexRoute,
}

const AppDirectoryPlacesIdRouteWithChildren =
  AppDirectoryPlacesIdRoute._addFileChildren(AppDirectoryPlacesIdRouteChildren)

interface AppDirectoryPlacesRouteChildren {
  AppDirectoryPlacesIdRoute: typeof AppDirectoryPlacesIdRouteWithChildren
  AppDirectoryPlacesCreateRoute: typeof AppDirectoryPlacesCreateRoute
  AppDirectoryPlacesIndexRoute: typeof AppDirectoryPlacesIndexRoute
}

const AppDirectoryPlacesRouteChildren: AppDirectoryPlacesRouteChildren = {
  AppDirectoryPlacesIdRoute: AppDirectoryPlacesIdRouteWithChildren,
  AppDirectoryPlacesCreateRoute: AppDirectoryPlacesCreateRoute,
  AppDirectoryPlacesIndexRoute: AppDirectoryPlacesIndexRoute,
}

const AppDirectoryPlacesRouteWithChildren =
  AppDirectoryPlacesRoute._addFileChildren(AppDirectoryPlacesRouteChildren)

interface AppDirectoryRouteChildren {
  AppDirectoryContactsRoute: typeof AppDirectoryContactsRouteWithChildren
  AppDirectoryPlacesRoute: typeof AppDirectoryPlacesRouteWithChildren
  AppDirectoryIndexRoute: typeof AppDirectoryIndexRoute
}

const AppDirectoryRouteChildren: AppDirectoryRouteChildren = {
  AppDirectoryContactsRoute: AppDirectoryContactsRouteWithChildren,
  AppDirectoryPlacesRoute: AppDirectoryPlacesRouteWithChildren,
  AppDirectoryIndexRoute: AppDirectoryIndexRoute,
}

const AppDirectoryRouteWithChildren = AppDirectoryRoute._addFileChildren(
  AppDirectoryRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDirectoryRoute: typeof AppDirectoryRouteWithChildren
  AppSandboxRoute: typeof AppSandboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDirectoryRoute: AppDirectoryRouteWithChildren,
  AppSandboxRoute: AppSandboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfileIdRoute: AppProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  ResetPasswordEncodedUserIdTokenRoute: ResetPasswordEncodedUserIdTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
