# Generated by Django 4.2.23 on 2025-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager'), ('admin', 'Admin'), ('super_admin', 'Super_Admin')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
