# Generated by Django 4.2.23 on 2025-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='default fullname', editable=False, max_length=511),
            preserve_default=False,
        ),
    ]
