# Generated by Django 4.2.23 on 2025-09-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_label'),
        ('account', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('company', 'username')},
        ),
    ]
