# Generated by Django 4.2.23 on 2026-03-01 15:28

import app.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_company'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.account.models.CustomUserManager()),
            ],
        ),
    ]
